#use_frameworks!

target 'YumiMediationAdapters_Example' do
  pod 'YumiMediationAdapters', :path => '../'

  target 'YumiMediationAdapters_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
